from __future__ import annotations

"""Commercial store interfaces (billing, usage, API keys)."""

from typing import Protocol, runtime_checkable

from backend.models.api_key_models import ApiKey
from backend.models.billing_models import CreditBalance, Invoice, PaymentAttempt, Subscription, UsageRecord


@runtime_checkable
class SubscriptionStore(Protocol):
    def save(self, subscription: Subscription) -> Subscription: ...
    def get(self, organization_id: str) -> Subscription | None: ...
    def delete(self, organization_id: str) -> bool: ...
    def clear(self) -> None: ...


@runtime_checkable
class InvoiceStore(Protocol):
    def save(self, invoice: Invoice) -> Invoice: ...
    def get(self, invoice_id: str) -> Invoice | None: ...
    def list(self, *, organization_id: str | None = None) -> list[Invoice]: ...
    def clear(self) -> None: ...


@runtime_checkable
class CreditStore(Protocol):
    def save(self, credit: CreditBalance) -> CreditBalance: ...
    def get(self, organization_id: str) -> CreditBalance | None: ...
    def clear(self) -> None: ...


@runtime_checkable
class PaymentStore(Protocol):
    def save(self, payment: PaymentAttempt) -> PaymentAttempt: ...
    def list(self, *, invoice_id: str | None = None) -> list[PaymentAttempt]: ...
    def clear(self) -> None: ...


@runtime_checkable
class UsageStore(Protocol):
    def add(self, record: UsageRecord) -> UsageRecord: ...
    def list(
        self,
        *,
        organization_id: str | None = None,
        workspace_id: str | None = None,
        user_id: str | None = None,
        metric: str | None = None,
    ) -> list[UsageRecord]: ...
    def clear(self) -> None: ...


@runtime_checkable
class ApiKeyStore(Protocol):
    def save(self, key: ApiKey) -> ApiKey: ...
    def get(self, key_id: str) -> ApiKey | None: ...
    def get_by_hash(self, key_hash: str) -> ApiKey | None: ...
    def list(self, *, organization_id: str | None = None) -> list[ApiKey]: ...
    def delete(self, key_id: str) -> bool: ...
    def clear(self) -> None: ...
